# Generated by Django 5.0.3 on 2025-08-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcadmin', '0002_internship'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='itcadmin_adminuser',
        ),
        migrations.AlterModelTable(
            name='internship',
            table='itcadmin_internship',
        ),
    ]
