# Generated by Django 5.0.3 on 2025-08-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcadmin', '0003_alter_adminuser_table_alter_internship_table'),
    ]

    operations = [
    ]
